### PR TITLE
unpinning version

### PR DESCRIPTION
**Pull request by rsivilli**

### CODE REVIEW

**Comment by rsivilli** [comment]
sorry for the mass ping, but seems I've been moved to just a member

**Comment by rsivilli** [comment]
normally I'd try to just pin to  minor of 4 (tested against 4), but I know that not all of these modules have been upgraded yet

**Comment by pjdufour-pac** [comment]
I've been working on updating many repos in dod-iac to support AWS provider 4.x.  I'll merge the PRs this week.  For example: https://github.com/dod-iac/terraform-aws-s3-bucket/pull/7.

Since you can use multiple version constraints at a time, I've converted `~> 3.0` to something like `>= 4.9, < 5.0`, `>= 3.0, < 5.0`, or whatever is appropriate.  `>= 3.0, < 5.0` would allow all `3.x` and `4.x` versions.  This seems like a good idea for avoiding "supporting"  major versions releases that the module hasn't been tested on.  However, `>= 3.0` isn't terrible, if the latest version is still compatible.  What I'd certainly prefer to not do is arbitrarily update to `>= 4.0` if `3.x` is still valid to allow more graceful updates.

**Comment by david-saeger** [comment]
Will this update require migration for infra that depends on these?

**Pull request merged**
